language: php

php:
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

env:
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer require symfony/security:${SYMFONY_VERSION} --no-update
    - composer require symfony/validator:${SYMFONY_VERSION} --no-update
    - composer update --dev --prefer-source

script: phpunit --coverage-text

notifications:
    email:
        - pierre+travis@ferm.io
